AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  intelagro-backend
Globals:
  Api:
    Cors:
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"
      AllowMethods: "'*'"
  Function:
    Timeout: 60
    Environment:
        Variables:
          JWT_SECRET: INTELAGRO_212730
          DB_HOST: 'ec2-3-142-171-178.us-east-2.compute.amazonaws.com'
          DB_USERNAME: 'intelagro'
          DB_PASSWORD: 'KSskNTiTCjYTDoEv'
          DB_NAME: 'intelagro'

Resources:
  # Functions
  login:
    Type: AWS::Serverless::Function    
    Properties:
      CodeUri: app/functions/login
      Handler: handler.login
      Runtime: python3.9
      Architectures:
        - arm64
      Events:
        loginEndpoint:
          Type: Api
          Properties:
            Path: /login
            Method: POST
      Layers:
        - !Ref httpApiLayer
        - !Ref databaseLayer
        - !Ref authLayer
  logout:
    Type: AWS::Serverless::Function    
    Properties:
      CodeUri: app/functions/logout
      Handler: handler.logout
      Runtime: python3.9
      Architectures:
        - arm64
      Events:
        loginEndpoint:
          Type: Api
          Properties:
            Path: /logout
            Method: POST
      Layers:
        - !Ref httpApiLayer
        - !Ref databaseLayer
        - !Ref authLayer
  controlSueloPost:
    Type: AWS::Serverless::Function    
    Properties:
      CodeUri: app/functions/control-suelo
      Handler: handler.post
      Runtime: python3.9
      Architectures:
        - arm64
      Events:
        controSueloPostEndpoint:
          Type: Api
          Properties:
            Path: /control-suelo
            Method: POST
      Layers:
        - !Ref httpApiLayer
        - !Ref databaseLayer
        - !Ref authLayer
  # Layers
  databaseLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: app/layers/database
      CompatibleRuntimes:
        - python3.9
    Metadata:
      BuildMethod: python3.9

  authLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: app/layers/auth
      CompatibleRuntimes:
        - python3.9
    Metadata:
      BuildMethod: python3.9

  httpApiLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: app/layers/httpApi
      CompatibleRuntimes:
        - python3.9
    Metadata:
      BuildMethod: python3.9